from sqlalchemy import Column, Integer, String, Float, Boolean, ForeignKey
from sqlalchemy.orm import relationship
from database import Base

class Player(Base):
    __tablename__ = "players"
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    batting_stats = relationship("BattingStats", back_populates="player", lazy="joined")
    pitching_stats = relationship("PitchingStats", back_populates="player", lazy="joined")

class Team(Base):
    __tablename__ = "teams"
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    division = Column(String, nullable=False)
    batting_stats = relationship("BattingStats", back_populates="team")
    pitching_stats = relationship("PitchingStats", back_populates="team")

class BattingStats(Base):
    __tablename__ = "batting_stats"
    id = Column(Integer, primary_key=True)
    player_id = Column(Integer, ForeignKey("players.id"))
    team_id = Column(Integer, ForeignKey("teams.id"))
    team_abbr = Column(String)
    season = Column(Integer)
    name = Column(String)
    age = Column(Integer)
    position = Column(String)
    war = Column(Float)
    games = Column(Integer)
    plate_appearances = Column(Integer)
    at_bats = Column(Integer)
    runs = Column(Integer)
    hits = Column(Integer)
    doubles = Column(Integer)
    triples = Column(Integer)
    homeruns = Column(Integer)
    rbi = Column(Integer)
    stolen_bases = Column(Integer)
    caught_stealing = Column(Integer)
    walks = Column(Integer)
    strikeouts = Column(Integer)
    batting_avg = Column(Float)
    obp = Column(Float)
    slugging = Column(Float)
    ops = Column(Float)
    ops_plus = Column(Float)
    roba = Column(Float)
    rbat = Column(Float)
    total_bases = Column(Integer)
    gidp = Column(Integer)
    hbp = Column(Integer)
    sac_hits = Column(Integer)
    sac_flies = Column(Integer)
    intentional_walks = Column(Integer)
    positions_played = Column(String)
    awards = Column(String)
    is_split = Column(Boolean, default=False)
    player = relationship("Player", back_populates="batting_stats", lazy="joined")
    team = relationship("Team", back_populates="batting_stats", lazy="joined")

class PitchingStats(Base):
    __tablename__ = "pitching_stats"
    id = Column(Integer, primary_key=True)
    player_id = Column(Integer, ForeignKey("players.id"))
    team_id = Column(Integer, ForeignKey("teams.id"))
    team_abbr = Column(String)
    season = Column(Integer)
    name = Column(String)
    age = Column(Integer)
    position = Column(String)
    war = Column(Float)
    wins = Column(Integer)
    losses = Column(Integer)
    win_loss_percentage = Column(Float)
    era = Column(Float)
    games = Column(Integer)
    games_started = Column(Integer)
    games_finished = Column(Integer)
    complete_games = Column(Integer)
    shutouts = Column(Integer)
    saves = Column(Integer)
    innings_pitched = Column(Float)
    hits = Column(Integer)
    runs = Column(Integer)
    earned_runs = Column(Integer)
    homeruns = Column(Integer)
    walks = Column(Integer)
    intentional_walks = Column(Integer)
    strikeouts = Column(Integer)
    hbp = Column(Integer)
    balks = Column(Integer)
    wild_pitches = Column(Integer)
    batters_faced = Column(Integer)
    era_plus = Column(Integer)
    fip = Column(Float)
    whip = Column(Float)
    hits_per_nine = Column(Float)
    hrs_per_nine = Column(Float)
    walks_per_nine = Column(Float)
    strikeouts_per_nine = Column(Float)
    strikeouts_per_walk = Column(Float)
    awards = Column(String)
    is_split = Column(Boolean, default=False)
    player = relationship("Player", back_populates="pitching_stats", lazy="joined")
    team = relationship("Team", back_populates="pitching_stats", lazy="joined")